_target_: src.module.AgeGenderPredictor
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.00001
scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 0.01
  steps_per_epoch: 10
  epochs: 10
gender_metric:
  _target_: torchmetrics.Accuracy
  num_classes: 2
  task: binary
age_metric:
  _target_: torchmetrics.MeanAbsoluteError
