_target_: src.module.AgeGenderPredictor
cfg:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.00001
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    gamma: 0.1
    step_size: 10
gender_metric:
  _target_: torchmetrics.Accuracy
  num_classes: 2
  task: binary
age_metric:
  _target_: torchmetrics.MeanAbsoluteError
