_target_: src.module.ObjectDetector
cfg:
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.0001
    weight_decay: 0.00001
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: True
    gamma: 0.1
    step_size: 10
loss:
  _target_: src.loss.DistanceBoxIoU_loss
model:
  _target_: src.model.Retinanet_resnet50
  num_classes: 2
  trainable_backbone_layers: 0
