_target_: src.datamodule.FaceDatamodule

dataset:
  _target_: src.datamodule.UTKFace
  image_dir: data/UTKFace

train_augm:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: 256
      width: 256
    - _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: albumentations.pytorch.ToTensorV2

val_augm:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: 256
      width: 256
    - _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: albumentations.pytorch.ToTensorV2

test_augm:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: 256
      width: 256
    - _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: albumentations.pytorch.ToTensorV2

loaders:
  train_loader:
    batch_size: 128
    shuffle: True
    num_workers: 11
  val_loader:
    batch_size: 64
    shuffle: False
    num_workers: 11
  test_loader:
    batch_size: 64
    shuffle: False
    num_workers: 11
