_target_: src.datamodule.FaceDatamodule

trainset:
  _target_: src.datamodule.WiderfaceDataset
  split: train
  transforms:
    _target_: albumentations.Compose
    transforms:
      - _target_: albumentations.Resize
        height: 256
        width: 256
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      - _target_: albumentations.pytorch.ToTensorV2

valset:
  _target_: src.datamodule.WiderfaceDataset
  split: validation
  transforms:
    _target_: albumentations.Compose
    transforms:
      - _target_: albumentations.Resize
        height: 256
        width: 256
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      - _target_: albumentations.pytorch.ToTensorV2

testset:
  _target_: src.datamodule.WiderfaceDataset
  split: test
  transforms:
    _target_: albumentations.Compose
    transforms:
      - _target_: albumentations.Resize
        height: 256
        width: 256
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      - _target_: albumentations.pytorch.ToTensorV2

loaders:
  train_loader:
    batch_size: 16
    shuffle: True
    num_workers: 11
  val_loader:
    batch_size: 32
    shuffle: False
    num_workers: 11
  test_loader:
    batch_size: 32
    shuffle: False
    num_workers: 11
