# @package _global_

defaults:
  - _self_
  - datamodule: UTKFace
  - module: facedetection

ckpt_path: None

seed: 42

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  devices: [0]
