# @package _global_

defaults:
  - _self_
  - datamodule: UTKFace
  - module: facedetection

task_name: Age_n_Gender_detection_Resnet18
seed: 42

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  devices: [0]
  max_epochs: 1000

logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: tb_logs
  name: ${task_name}

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 3
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_loss
    mode: min
    filename: best
    save_weights_only: False
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
