# @package _global_

defaults:
  - _self_
  - datamodule: UTKFace
  - module: facedetection

seed: 42

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  devices: [0]
  max_epochs: -1

logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: tb_logs
  name: ${task_name}
